-- AlterTable
ALTER TABLE `customization` MODIFY `logo` BOOLEAN NULL DEFAULT true,
    MODIFY `contact` BOOLEAN NULL DEFAULT true,
    MODIFY `about` BOOLEAN NULL DEFAULT true,
    MODIFY `columns` INTEGER NULL DEFAULT 2,
    MODIFY `radius` INTEGER NULL DEFAULT 0,
    MODIFY `primaryBtn_color` VARCHAR(191) NULL DEFAULT '#ffffff',
    MODIFY `primaryBtn_background` VARCHAR(191) NULL DEFAULT '#3244a8',
    MODIFY `secondaryBtn_color` VARCHAR(191) NULL DEFAULT '#3244a8',
    MODIFY `secondaryBtn_border` VARCHAR(191) NULL DEFAULT '#3244a8',
    MODIFY `navigation_color` VARCHAR(191) NULL DEFAULT '#36438a',
    MODIFY `main_color` VARCHAR(191) NULL DEFAULT '#6676cc',
    MODIFY `footer_color` VARCHAR(191) NULL DEFAULT '#36438a',
    MODIFY `instagram` BOOLEAN NULL DEFAULT false,
    MODIFY `instagramUrl` VARCHAR(191) NULL,
    MODIFY `facebook` BOOLEAN NULL DEFAULT false,
    MODIFY `facebookUrl` VARCHAR(191) NULL,
    MODIFY `tiktok` BOOLEAN NULL DEFAULT false,
    MODIFY `tiktokUrl` VARCHAR(191) NULL,
    MODIFY `youtube` BOOLEAN NULL DEFAULT false,
    MODIFY `youtubeUrl` VARCHAR(191) NULL,
    MODIFY `footer_text` VARCHAR(191) NULL;
